I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 9, in script
    python:
  File "game/script.rpy", line 11, in <module>
    npc1 = NPC("Friendly", 80, True, image="images/character.jpg")
TypeError: __init__() got multiple values for keyword argument 'image'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 9, in script
    python:
  File "/Applications/renpy-7.3.5-sdk/renpy/ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/renpy-7.3.5-sdk/renpy/python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 11, in <module>
    npc1 = NPC("Friendly", 80, True, image="images/character.jpg")
TypeError: __init__() got multiple values for keyword argument 'image'

Darwin-19.4.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
Demo 1.0
Wed May 20 22:50:32 2020
